# Generated by Django 4.2.6 on 2023-10-21 19:56

from django.db import migrations, models
import station_user.models


class Migration(migrations.Migration):
    dependencies = [
        ("station_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", station_user.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
