# Generated by Django 4.2.6 on 2023-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="crew",
            field=models.ManyToManyField(
                related_name="journeys", to="station_app.crew"
            ),
        ),
    ]
