# Generated by Django 4.2.6 on 2023-10-21 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station_app", "0003_journey_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="destination_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 22, 9, 45, 26, 837932)
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="source_datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
