# Generated by Django 4.2.6 on 2023-10-21 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "station_app",
            "0004_route_destination_datetime_route_source_datetime",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="destination_datetime",
        ),
        migrations.RemoveField(
            model_name="route",
            name="source_datetime",
        ),
    ]
