# Generated by Django 4.2.6 on 2023-10-22 21:45

from django.db import migrations, models
import station_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("station_app", "0005_remove_route_destination_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="profile_image",
            field=models.ImageField(
                null=True, upload_to=station_app.models.crew_image_file_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("journey", "carriage", "seat")},
        ),
    ]
